### ISSUE TITLE
Autocomplete Isnt working

### ISSUE THREAD

**Issue by bradgoodman** [Dannyzen/cf-zsh-autocomplete-plugin#6]
- Plugin is installed in .oh-my-zsh/plugins folder
- Antigen is installed and has dannyzen/cf-zsh-autocomplete-plugin @ master 
- Currently on CLI version 6.26
Unsure of what exactly I need to try next

**Comment by Dannyzen** [comment]
Hey @bradgoodman If you source the plugin directly are you able to get completions?

**Comment by bradgoodman** [comment]
Would you mind sharing how I can go about sourcing the plugin to perform that testing. I've tried sourcing cf, but was unsuccessful in getting the autocompletion for cf working.

**Comment by Dannyzen** [comment]
Certainly. 
1. Clone the project
1. create a new file called .test and paste the below into it, replace the cloned path in the first line

```
fpath=(/path/to/cloned/project $fpath) 
 
# compsys initialization
autoload -U compinit
compinit
# show menu when # of options => 2
zstyle ':completion:*' menu select=2
```
1. source the .test file by running: `source .test`
1. type `cf b` and then press `<tab>`
 
You should see something like this:
![image](https://cloud.githubusercontent.com/assets/659908/26425479/dff643c4-40a2-11e7-9555-69a5a396a3b7.png)

**Comment by bradgoodman** [comment]
```fpath=(~/Downloads/cf-zsh-autocomplete-plugin $fpath)
# compsys initialization
autoload -U compinit
compinit
# show menu when # of options => 2
zstyle ':completion:*' menu select=2```

Error:   ~/Downloads  source .test
source: no such file or directory: .zshrc
  ~/Downloads  vi .test

**Comment by bradgoodman** [comment]
<img width="328" alt="screen shot 2017-05-24 at 4 28 29 pm" src="https://cloud.githubusercontent.com/assets/16807293/26426444/3216117a-409e-11e7-966f-bd40a17acf69.png">
<img width="263" alt="screen shot 2017-05-24 at 4 29 24 pm" src="https://cloud.githubusercontent.com/assets/16807293/26426445/32300b8e-409e-11e7-87a4-9e2803013a0e.png">

**Comment by Dannyzen** [comment]
hey @bradgoodman I'm not sure why the output of your console states that `.zshrc` does not exist. 
If you isolate each line of that file, which line causes the `source: no such file or directory: .zshrc` error?

**Comment by Dannyzen** [comment]
@bradgoodman how's everything going? Were you able to learn more or resolve your issue?

**Comment by bradgoodman** [comment]
I've commented out each line of the .test file and still receive the `source: no such file or directory: .zshrc` error while running to `source .test` I'm not sure what to try next.

**Comment by Dannyzen** [comment]
@bradgoodman it sounds like you might have an issue with your zsh setup if after sourcing a commented out file you're getting a `source: no such file or directory: .zshrc`. I'll do my best to help you but I want to note that you may have bigger problems outside the scope of this project.

One route we can try to take is to use the https://github.com/zsh-users/zsh-completions which contains the cf-zsh-autocomplete-plugin. I personally use the [antigen approach](https://github.com/zsh-users/zsh-completions#using-zsh-frameworks) for installation. Give that a shot and let me know how it goes.

**Comment by bradgoodman** [comment]
So I was able to get past the error `source: no such file or directory: .zshrc` I now receive this error.
![screen shot 2017-05-30 at 8 37 18 am](https://cloud.githubusercontent.com/assets/16807293/26585922/3f79e5c0-4513-11e7-92ff-b732f4206e97.png)

**Comment by Dannyzen** [comment]
Hey @bradgoodman note the original script I pasted, the 3rd line contains a comment. Give it another try.


```
fpath=(/path/to/cloned/project $fpath) 
 
# compsys initialization
autoload -U compinit
compinit
# show menu when # of options => 2
zstyle ':completion:*' menu select=2
```

**Comment by bradgoodman** [comment]
I commented out those lines and was able to use the autocomplete option.

**Comment by Dannyzen** [comment]
Great. Are you able to install the plugin as described in the [README](https://github.com/Dannyzen/cf-zsh-autocomplete-plugin/blob/master/README.md)?

**Comment by bradgoodman** [comment]
<img width="632" alt="screen shot 2017-05-30 at 10 14 12 pm" src="https://cloud.githubusercontent.com/assets/16807293/26614382/ae27f3be-4585-11e7-81d4-2a3bb1dd3467.png">
<img width="540" alt="screen shot 2017-05-30 at 10 14 56 pm" src="https://cloud.githubusercontent.com/assets/16807293/26614383/ae627f02-4585-11e7-8472-b2097dc6b2ef.png">
<img width="283" alt="screen shot 2017-05-30 at 10 15 09 pm" src="https://cloud.githubusercontent.com/assets/16807293/26614384/ae73e21a-4585-11e7-9e85-57aba08565ee.png">
<img width="230" alt="screen shot 2017-05-30 at 10 17 29 pm" src="https://cloud.githubusercontent.com/assets/16807293/26614402/cc7fe240-4585-11e7-956a-f1dad649a4a8.png">

**Comment by Dannyzen** [comment]
Great! Feel free to close this issue.

**Comment by bradgoodman** [comment]
Unfortunately, although everything appears to be setup appropriately the cf auto completion still isn't working for some reason.

**Comment by Dannyzen** [comment]
I see. If you try another autocomplete script, does it work? I want to
assure we're isolating the issue to either the script itself or your setup.

**Comment by bradgoodman** [comment]
Can you think of any others that would be good to try? I don't have any other autocomplete scripts setup.

**Comment by Dannyzen** [comment]
Yeah, the [jq autocomplete](https://github.com/zsh-users/zsh-completions/blob/master/src/_jq) is pretty good.  Download [jq](https://stedolan.github.io/jq/) for your OS and paste the contents of the autocomplete plugin into your oh-my-zsh plugin folder and include it in your `.zshrc` plugin declaration, effectively copying the installation methodology of this repository. LMK if you have any questions regarding installation.

**Comment by Dannyzen** [comment]
@bradgoodman How are we looking? Is this good to close or can I provide any more support?

**Comment by bradgoodman** [comment]
I wasnt able to get JQ working either. I ended up kinda working around the issue by creating a file called cf-autocomplete with the code above in the folder /Users/brad/.oh-my-zsh/plugins/cf and sourcing the file in my .zshrc file. Kinda janky, but it seems to be working.

**Comment by Dannyzen** [comment]
@bradgoodman glad to hear you were able to get it working.
